export const animations = {
    STAND: 'stand',
    RUN: 'run',
    CROUCH: 'crouch',
    CROUCHING: 'crouching',
    UNCROUCH: 'uncrouch',
    LAND: 'land',
    FORWARD_ROLL: 'forward_roll',
    BACKWARD_ROLL: 'backward_roll',
    //JUMP: 'jump',
    STAND_JUMP: 'stand_jump',
    RUN_JUMP: 'run_jump',
    STAND_FALL: 'stand_fall',
    FALL_ROLL: 'fall_roll',
    FORWARD_FALL: 'forward_fall',
    BACKWARD_FALL: 'backward_fall',
    SHOOT: 'shoot',
    GRENADE_TOSS: 'grenade_toss',
    PUCK_TOSS: 'puck_toss',
    PARACHUTE: 'parachute',
    HOOK: 'hook',
    CLIMB: 'climb',
    VICTORY: 'victory',
    ROPE_VICTORY: 'rope_victory',
    DISINTEGRATE: 'disintegrate',
    VAPORIZE: 'vaporize',
    TAUNT: 'taunt',
    FLEX: 'flex',
    MAGNET: 'magnet',
    EMPTY: 'empty',
    TRAPPED: 'trapped',
    NONE: 'none' // special: stops current animation
}