export const animations = {
    STAND: "stand",
    RUN: "run",
    CROUCHED: "crouched",
    CROUCHING: "crouching",
    UNCROUCH: "uncrouch",
    FORWARD_ROLL: "forward_roll",
    BACKWARD_ROLL: "backward_roll",
    STAND_JUMP: "stand_jump",
    RUN_JUMP: "run_jump",
    STAND_BOOTS_JUMP: "stand_boots_jump",
    RUN_BOOTS_JUMP: "run_boots_jump",
    STAND_FALL: "stand_fall",
    FORWARD_FALL: "forward_fall",
    BACKWARD_FALL: "backward_fall",
    CLIMB_UP: "climb_up",
    CLIMB_DOWN: "climb_down",
    DISINTEGRATED: "disintegrated",
    SKULLED: "skulled",
    VICTORY_DANCE: "victory_dance",
    ROPE_VICTORY: "rope_victory",
    VICTORY_FLEX: "victory_flex",
    SHOOT: "shoot",
    GRENADE_TOSS: "grenade_toss",
    PUCK_TOSS: "puck_toss",
    MINE_PLANT: "mine_plant",
    PARACHUTE: "parachute",

    // FALL_ROLL: "fall_roll",
    HOOK: "hook",
    CLIMB: "climb",
    VAPORIZE: "vaporize",
    TAUNT: "taunt",
    MAGNET: "magnet",
    EMPTY: "empty",
    TRAPPED: "trapped",
    NONE: "none" // special: stops current animation
};
